"""Domain error code constants."""

INVALID_GRID_SIZE = "INVALID_GRID_SIZE"
INVALID_EMPTY_COUNT = "INVALID_EMPTY_COUNT"
INVALID_MISSING_COUNT = "INVALID_MISSING_COUNT"
NO_VALID_COMPLETION = "NO_VALID_COMPLETION"
